from __future__ import unicode_literals


__ie_list = [
    ('abc', ['ABCIE']),
    ('academicearth', ['AcademicEarthCourseIE']),
    ('addanime', ['AddAnimeIE']),
    ('adultswim', ['AdultSwimIE']),
    ('aftonbladet', ['AftonbladetIE']),
    ('anitube', ['AnitubeIE']),
    ('anysex', ['AnySexIE']),
    ('aol', ['AolIE']),
    ('allocine', ['AllocineIE']),
    ('aparat', ['AparatIE']),
    ('appletrailers', ['AppleTrailersIE']),
    ('archiveorg', ['ArchiveOrgIE']),
    ('ard', [
        'ARDIE',
        'ARDMediathekIE',
    ]),
    ('arte', [
        'ArteTvIE',
        'ArteTVPlus7IE',
        'ArteTVCreativeIE',
        'ArteTVConcertIE',
        'ArteTVFutureIE',
        'ArteTVDDCIE',
        'ArteTVEmbedIE',
    ]),
    ('audiomack', ['AudiomackIE']),
    ('auengine', ['AUEngineIE']),
    ('bambuser', [
        'BambuserIE',
        'BambuserChannelIE',
    ]),
    ('bandcamp', [
        'BandcampIE',
        'BandcampAlbumIE',
    ]),
    ('bbccouk', ['BBCCoUkIE']),
    ('beeg', ['BeegIE']),
    ('behindkink', ['BehindKinkIE']),
    ('bild', ['BildIE']),
    ('bilibili', ['BiliBiliIE']),
    ('blinkx', ['BlinkxIE']),
    ('bliptv', [
        'BlipTVIE',
        'BlipTVUserIE',
    ]),
    ('bloomberg', ['BloombergIE']),
    ('bpb', ['BpbIE']),
    ('br', ['BRIE']),
    ('breakcom', ['BreakIE']),
    ('brightcove', ['BrightcoveIE']),
    ('byutv', ['BYUtvIE']),
    ('c56', ['C56IE']),
    ('canal13cl', ['Canal13clIE']),
    ('canalplus', ['CanalplusIE']),
    ('canalc2', ['Canalc2IE']),
    ('cbs', ['CBSIE']),
    ('cbsnews', ['CBSNewsIE']),
    ('ceskatelevize', ['CeskaTelevizeIE']),
    ('channel9', ['Channel9IE']),
    ('chilloutzone', ['ChilloutzoneIE']),
    ('cinemassacre', ['CinemassacreIE']),
    ('clipfish', ['ClipfishIE']),
    ('cliphunter', ['CliphunterIE']),
    ('clipsyndicate', ['ClipsyndicateIE']),
    ('cloudy', ['CloudyIE']),
    ('clubic', ['ClubicIE']),
    ('cmt', ['CMTIE']),
    ('cnet', ['CNETIE']),
    ('cnn', [
        'CNNIE',
        'CNNBlogsIE',
    ]),
    ('collegehumor', ['CollegeHumorIE']),
    ('comedycentral', [
        'ComedyCentralIE',
        'ComedyCentralShowsIE',
    ]),
    ('condenast', ['CondeNastIE']),
    ('cracked', ['CrackedIE']),
    ('criterion', ['CriterionIE']),
    ('crunchyroll', [
        'CrunchyrollIE',
        'CrunchyrollShowPlaylistIE',
    ]),
    ('cspan', ['CSpanIE']),
    ('dailymotion', [
        'DailymotionIE',
        'DailymotionPlaylistIE',
        'DailymotionUserIE',
    ]),
    ('daum', ['DaumIE']),
    ('dbtv', ['DBTVIE']),
    ('deezer', ['DeezerPlaylistIE']),
    ('dfb', ['DFBIE']),
    ('dotsub', ['DotsubIE']),
    ('dreisat', ['DreiSatIE']),
    ('drtuber', ['DrTuberIE']),
    ('drtv', ['DRTVIE']),
    ('dump', ['DumpIE']),
    ('defense', ['DefenseGouvFrIE']),
    ('discovery', ['DiscoveryIE']),
    ('divxstage', ['DivxStageIE']),
    ('dropbox', ['DropboxIE']),
    ('ebaumsworld', ['EbaumsWorldIE']),
    ('ehow', ['EHowIE']),
    ('eighttracks', ['EightTracksIE']),
    ('einthusan', ['EinthusanIE']),
    ('eitb', ['EitbIE']),
    ('ellentv', [
        'EllenTVIE',
        'EllenTVClipsIE',
    ]),
    ('elpais', ['ElPaisIE']),
    ('empflix', ['EMPFlixIE']),
    ('engadget', ['EngadgetIE']),
    ('eporner', ['EpornerIE']),
    ('escapist', ['EscapistIE']),
    ('everyonesmixtape', ['EveryonesMixtapeIE']),
    ('exfm', ['ExfmIE']),
    ('expotv', ['ExpoTVIE']),
    ('extremetube', ['ExtremeTubeIE']),
    ('facebook', ['FacebookIE']),
    ('faz', ['FazIE']),
    ('fc2', ['FC2IE']),
    ('firedrive', ['FiredriveIE']),
    ('firstpost', ['FirstpostIE']),
    ('firsttv', ['FirstTVIE']),
    ('fivemin', ['FiveMinIE']),
    ('fktv', [
        'FKTVIE',
        'FKTVPosteckeIE',
    ]),
    ('flickr', ['FlickrIE']),
    ('folketinget', ['FolketingetIE']),
    ('fourtube', ['FourTubeIE']),
    ('franceculture', ['FranceCultureIE']),
    ('franceinter', ['FranceInterIE']),
    ('francetv', [
        'PluzzIE',
        'FranceTvInfoIE',
        'FranceTVIE',
        'GenerationQuoiIE',
        'CultureboxIE',
    ]),
    ('freesound', ['FreesoundIE']),
    ('freespeech', ['FreespeechIE']),
    ('freevideo', ['FreeVideoIE']),
    ('funnyordie', ['FunnyOrDieIE']),
    ('gamekings', ['GamekingsIE']),
    ('gameone', [
        'GameOneIE',
        'GameOnePlaylistIE',
    ]),
    ('gamespot', ['GameSpotIE']),
    ('gamestar', ['GameStarIE']),
    ('gametrailers', ['GametrailersIE']),
    ('gdcvault', ['GDCVaultIE']),
    ('generic', ['GenericIE']),
    ('glide', ['GlideIE']),
    ('globo', ['GloboIE']),
    ('godtube', ['GodTubeIE']),
    ('goldenmoustache', ['GoldenMoustacheIE']),
    ('golem', ['GolemIE']),
    ('googleplus', ['GooglePlusIE']),
    ('googlesearch', ['GoogleSearchIE']),
    ('gorillavid', ['GorillaVidIE']),
    ('goshgay', ['GoshgayIE']),
    ('grooveshark', ['GroovesharkIE']),
    ('hark', ['HarkIE']),
    ('heise', ['HeiseIE']),
    ('helsinki', ['HelsinkiIE']),
    ('hentaistigma', ['HentaiStigmaIE']),
    ('hornbunny', ['HornBunnyIE']),
    ('hostingbulk', ['HostingBulkIE']),
    ('hotnewhiphop', ['HotNewHipHopIE']),
    ('howcast', ['HowcastIE']),
    ('howstuffworks', ['HowStuffWorksIE']),
    ('huffpost', ['HuffPostIE']),
    ('hypem', ['HypemIE']),
    ('iconosquare', ['IconosquareIE']),
    ('ign', [
        'IGNIE',
        'OneUPIE',
    ]),
    ('imdb', [
        'ImdbIE',
        'ImdbListIE',
    ]),
    ('ina', ['InaIE']),
    ('infoq', ['InfoQIE']),
    ('instagram', [
        'InstagramIE',
        'InstagramUserIE',
    ]),
    ('internetvideoarchive', ['InternetVideoArchiveIE']),
    ('iprima', ['IPrimaIE']),
    ('ivi', [
        'IviIE',
        'IviCompilationIE',
    ]),
    ('izlesene', ['IzleseneIE']),
    ('jadorecettepub', ['JadoreCettePubIE']),
    ('jeuxvideo', ['JeuxVideoIE']),
    ('jove', ['JoveIE']),
    ('jukebox', ['JukeboxIE']),
    ('jpopsukitv', ['JpopsukiIE']),
    ('kankan', ['KankanIE']),
    ('keezmovies', ['KeezMoviesIE']),
    ('khanacademy', ['KhanAcademyIE']),
    ('kickstarter', ['KickStarterIE']),
    ('keek', ['KeekIE']),
    ('kontrtube', ['KontrTubeIE']),
    ('krasview', ['KrasViewIE']),
    ('ku6', ['Ku6IE']),
    ('la7', ['LA7IE']),
    ('laola1tv', ['Laola1TvIE']),
    ('lifenews', ['LifeNewsIE']),
    ('liveleak', ['LiveLeakIE']),
    ('livestream', [
        'LivestreamIE',
        'LivestreamOriginalIE',
        'LivestreamShortenerIE',
    ]),
    ('lrt', ['LRTIE']),
    ('lynda', [
        'LyndaIE',
        'LyndaCourseIE',
    ]),
    ('m6', ['M6IE']),
    ('macgamestore', ['MacGameStoreIE']),
    ('mailru', ['MailRuIE']),
    ('malemotion', ['MalemotionIE']),
    ('mdr', ['MDRIE']),
    ('metacafe', ['MetacafeIE']),
    ('metacritic', ['MetacriticIE']),
    ('mgoon', ['MgoonIE']),
    ('ministrygrid', ['MinistryGridIE']),
    ('mit', [
        'TechTVMITIE',
        'MITIE',
        'OCWMITIE',
    ]),
    ('mitele', ['MiTeleIE']),
    ('mixcloud', ['MixcloudIE']),
    ('mlb', ['MLBIE']),
    ('mpora', ['MporaIE']),
    ('moevideo', ['MoeVideoIE']),
    ('mofosex', ['MofosexIE']),
    ('mojvideo', ['MojvideoIE']),
    ('moniker', ['MonikerIE']),
    ('mooshare', ['MooshareIE']),
    ('morningstar', ['MorningstarIE']),
    ('motherless', ['MotherlessIE']),
    ('motorsport', ['MotorsportIE']),
    ('movieclips', ['MovieClipsIE']),
    ('moviezine', ['MoviezineIE']),
    ('movshare', ['MovShareIE']),
    ('mtv', [
        'MTVIE',
        'MTVServicesEmbeddedIE',
        'MTVIggyIE',
    ]),
    ('muenchentv', ['MuenchenTVIE']),
    ('musicplayon', ['MusicPlayOnIE']),
    ('musicvault', ['MusicVaultIE']),
    ('muzu', ['MuzuTVIE']),
    ('myspace', ['MySpaceIE']),
    ('myspass', ['MySpassIE']),
    ('myvideo', ['MyVideoIE']),
    ('naver', ['NaverIE']),
    ('nba', ['NBAIE']),
    ('nbc', [
        'NBCIE',
        'NBCNewsIE',
    ]),
    ('ndr', ['NDRIE']),
    ('ndtv', ['NDTVIE']),
    ('newgrounds', ['NewgroundsIE']),
    ('newstube', ['NewstubeIE']),
    ('nfb', ['NFBIE']),
    ('nfl', ['NFLIE']),
    ('nhl', [
        'NHLIE',
        'NHLVideocenterIE',
    ]),
    ('niconico', [
        'NiconicoIE',
        'NiconicoPlaylistIE',
    ]),
    ('ninegag', ['NineGagIE']),
    ('noco', ['NocoIE']),
    ('normalboots', ['NormalbootsIE']),
    ('nosvideo', ['NosVideoIE']),
    ('novamov', ['NovaMovIE']),
    ('nowness', ['NownessIE']),
    ('nowvideo', ['NowVideoIE']),
    ('npo', [
        'NPOIE',
        'TegenlichtVproIE',
    ]),
    ('nrk', [
        'NRKIE',
        'NRKTVIE',
    ]),
    ('ntv', ['NTVIE']),
    ('nytimes', ['NYTimesIE']),
    ('nuvid', ['NuvidIE']),
    ('oktoberfesttv', ['OktoberfestTVIE']),
    ('ooyala', ['OoyalaIE']),
    ('orf', [
        'ORFTVthekIE',
        'ORFOE1IE',
        'ORFFM4IE',
    ]),
    ('parliamentliveuk', ['ParliamentLiveUKIE']),
    ('patreon', ['PatreonIE']),
    ('pbs', ['PBSIE']),
    ('phoenix', ['PhoenixIE']),
    ('photobucket', ['PhotobucketIE']),
    ('planetaplay', ['PlanetaPlayIE']),
    ('played', ['PlayedIE']),
    ('playfm', ['PlayFMIE']),
    ('playvid', ['PlayvidIE']),
    ('podomatic', ['PodomaticIE']),
    ('pornhd', ['PornHdIE']),
    ('pornhub', ['PornHubIE']),
    ('pornotube', ['PornotubeIE']),
    ('pornoxo', ['PornoXOIE']),
    ('promptfile', ['PromptFileIE']),
    ('prosiebensat1', ['ProSiebenSat1IE']),
    ('pyvideo', ['PyvideoIE']),
    ('quickvid', ['QuickVidIE']),
    ('radiofrance', ['RadioFranceIE']),
    ('rai', ['RaiIE']),
    ('rbmaradio', ['RBMARadioIE']),
    ('redtube', ['RedTubeIE']),
    ('reverbnation', ['ReverbNationIE']),
    ('ringtv', ['RingTVIE']),
    ('ro220', ['Ro220IE']),
    ('rottentomatoes', ['RottenTomatoesIE']),
    ('roxwel', ['RoxwelIE']),
    ('rtbf', ['RTBFIE']),
    ('rtlnl', ['RtlXlIE']),
    ('rtlnow', ['RTLnowIE']),
    ('rts', ['RTSIE']),
    ('rtve', [
        'RTVEALaCartaIE',
        'RTVELiveIE',
    ]),
    ('ruhd', ['RUHDIE']),
    ('rutube', [
        'RutubeIE',
        'RutubeChannelIE',
        'RutubeMovieIE',
        'RutubePersonIE',
    ]),
    ('rutv', ['RUTVIE']),
    ('sapo', ['SapoIE']),
    ('savefrom', ['SaveFromIE']),
    ('sbs', ['SBSIE']),
    ('scivee', ['SciVeeIE']),
    ('screencast', ['ScreencastIE']),
    ('servingsys', ['ServingSysIE']),
    ('sexu', ['SexuIE']),
    ('sexykarma', ['SexyKarmaIE']),
    ('shared', ['SharedIE']),
    ('sharesix', ['ShareSixIE']),
    ('sina', ['SinaIE']),
    ('slideshare', ['SlideshareIE']),
    ('slutload', ['SlutloadIE']),
    ('smotri', [
        'SmotriIE',
        'SmotriCommunityIE',
        'SmotriUserIE',
        'SmotriBroadcastIE',
    ]),
    ('snotr', ['SnotrIE']),
    ('sockshare', ['SockshareIE']),
    ('sohu', ['SohuIE']),
    ('soundcloud', [
        'SoundcloudIE',
        'SoundcloudSetIE',
        'SoundcloudUserIE',
        'SoundcloudPlaylistIE',
    ]),
    ('soundgasm', ['SoundgasmIE']),
    ('southpark', [
        'SouthParkIE',
        'SouthparkDeIE',
    ]),
    ('space', ['SpaceIE']),
    ('spankwire', ['SpankwireIE']),
    ('spiegel', [
        'SpiegelIE',
        'SpiegelArticleIE',
    ]),
    ('spiegeltv', ['SpiegeltvIE']),
    ('spike', ['SpikeIE']),
    ('sport5', ['Sport5IE']),
    ('sportbox', ['SportBoxIE']),
    ('sportdeutschland', ['SportDeutschlandIE']),
    ('srmediathek', ['SRMediathekIE']),
    ('stanfordoc', ['StanfordOpenClassroomIE']),
    ('steam', ['SteamIE']),
    ('streamcloud', ['StreamcloudIE']),
    ('streamcz', ['StreamCZIE']),
    ('sunporno', ['SunPornoIE']),
    ('swrmediathek', ['SWRMediathekIE']),
    ('syfy', ['SyfyIE']),
    ('sztvhu', ['SztvHuIE']),
    ('tagesschau', ['TagesschauIE']),
    ('tapely', ['TapelyIE']),
    ('tass', ['TassIE']),
    ('teachertube', [
        'TeacherTubeIE',
        'TeacherTubeUserIE',
    ]),
    ('teachingchannel', ['TeachingChannelIE']),
    ('teamcoco', ['TeamcocoIE']),
    ('techtalks', ['TechTalksIE']),
    ('ted', ['TEDIE']),
    ('telebruxelles', ['TeleBruxellesIE']),
    ('telecinco', ['TelecincoIE']),
    ('telemb', ['TeleMBIE']),
    ('tenplay', ['TenPlayIE']),
    ('testurl', ['TestURLIE']),
    ('tf1', ['TF1IE']),
    ('theonion', ['TheOnionIE']),
    ('theplatform', ['ThePlatformIE']),
    ('thesixtyone', ['TheSixtyOneIE']),
    ('thisav', ['ThisAVIE']),
    ('tinypic', ['TinyPicIE']),
    ('tlc', [
        'TlcIE',
        'TlcDeIE',
    ]),
    ('tmz', ['TMZIE']),
    ('tnaflix', ['TNAFlixIE']),
    ('thvideo', [
        'THVideoIE',
        'THVideoPlaylistIE',
    ]),
    ('toutv', ['TouTvIE']),
    ('toypics', [
        'ToypicsUserIE',
        'ToypicsIE',
    ]),
    ('traileraddict', ['TrailerAddictIE']),
    ('trilulilu', ['TriluliluIE']),
    ('trutube', ['TruTubeIE']),
    ('tube8', ['Tube8IE']),
    ('tudou', ['TudouIE']),
    ('tumblr', ['TumblrIE']),
    ('tunein', ['TuneInIE']),
    ('turbo', ['TurboIE']),
    ('tutv', ['TutvIE']),
    ('tvigle', ['TvigleIE']),
    ('tvp', ['TvpIE']),
    ('tvplay', ['TVPlayIE']),
    ('twitch', ['TwitchIE']),
    ('ubu', ['UbuIE']),
    ('udemy', [
        'UdemyIE',
        'UdemyCourseIE',
    ]),
    ('unistra', ['UnistraIE']),
    ('urort', ['UrortIE']),
    ('ustream', [
        'UstreamIE',
        'UstreamChannelIE',
    ]),
    ('vbox7', ['Vbox7IE']),
    ('veehd', ['VeeHDIE']),
    ('veoh', ['VeohIE']),
    ('vesti', ['VestiIE']),
    ('vevo', ['VevoIE']),
    ('vgtv', ['VGTVIE']),
    ('vh1', ['VH1IE']),
    ('vice', ['ViceIE']),
    ('viddler', ['ViddlerIE']),
    ('videobam', ['VideoBamIE']),
    ('videodetective', ['VideoDetectiveIE']),
    ('videolecturesnet', ['VideoLecturesNetIE']),
    ('videofyme', ['VideofyMeIE']),
    ('videomega', ['VideoMegaIE']),
    ('videopremium', ['VideoPremiumIE']),
    ('videott', ['VideoTtIE']),
    ('videoweed', ['VideoWeedIE']),
    ('vidme', ['VidmeIE']),
    ('vidzi', ['VidziIE']),
    ('vimeo', [
        'VimeoIE',
        'VimeoAlbumIE',
        'VimeoChannelIE',
        'VimeoGroupsIE',
        'VimeoLikesIE',
        'VimeoReviewIE',
        'VimeoUserIE',
        'VimeoWatchLaterIE',
    ]),
    ('vimple', ['VimpleIE']),
    ('vine', [
        'VineIE',
        'VineUserIE',
    ]),
    ('viki', ['VikiIE']),
    ('vk', [
        'VKIE',
        'VKUserVideosIE',
    ]),
    ('vodlocker', ['VodlockerIE']),
    ('vporn', ['VpornIE']),
    ('vrt', ['VRTIE']),
    ('vube', ['VubeIE']),
    ('vuclip', ['VuClipIE']),
    ('vulture', ['VultureIE']),
    ('walla', ['WallaIE']),
    ('washingtonpost', ['WashingtonPostIE']),
    ('wat', ['WatIE']),
    ('wayofthemaster', ['WayOfTheMasterIE']),
    ('wdr', [
        'WDRIE',
        'WDRMobileIE',
        'WDRMausIE',
    ]),
    ('weibo', ['WeiboIE']),
    ('wimp', ['WimpIE']),
    ('wistia', ['WistiaIE']),
    ('worldstarhiphop', ['WorldStarHipHopIE']),
    ('wrzuta', ['WrzutaIE']),
    ('xbef', ['XBefIE']),
    ('xboxclips', ['XboxClipsIE']),
    ('xhamster', ['XHamsterIE']),
    ('xminus', ['XMinusIE']),
    ('xnxx', ['XNXXIE']),
    ('xvideos', ['XVideosIE']),
    ('xtube', [
        'XTubeUserIE',
        'XTubeIE',
    ]),
    ('yahoo', [
        'YahooIE',
        'YahooSearchIE',
    ]),
    ('ynet', ['YnetIE']),
    ('youjizz', ['YouJizzIE']),
    ('youku', ['YoukuIE']),
    ('youporn', ['YouPornIE']),
    ('yourupload', ['YourUploadIE']),
    ('youtube', [
        'YoutubeIE',
        'YoutubeChannelIE',
        'YoutubeFavouritesIE',
        'YoutubeHistoryIE',
        'YoutubePlaylistIE',
        'YoutubeRecommendedIE',
        'YoutubeSearchDateIE',
        'YoutubeSearchIE',
        'YoutubeSearchURLIE',
        'YoutubeShowIE',
        'YoutubeSubscriptionsIE',
        'YoutubeTopListIE',
        'YoutubeTruncatedURLIE',
        'YoutubeUserIE',
        'YoutubeWatchLaterIE',
    ]),
    ('zdf', ['ZDFIE']),
    ('zingmp3', [
        'ZingMp3SongIE',
        'ZingMp3AlbumIE',
    ]),
]

class CachedGenerator(object):
    def __init__(self, generator):
        self.generator = generator
        self.cached = []

    def __iter__(self):
        for cached_result in self.cached:
            yield cached_result
        for result in self.generator:
            self.cached.append(result)
            yield result

def _load_extractors():
    def sort_key(import_info):
        modname = import_info[0]
        if modname == 'generic':
            return -20
        return 0
    _sorted = sorted(__ie_list, key=sort_key, reverse=True)
    for (modname, ies) in _sorted:
        mod = __import__(modname, globals(), locals(), fromlist=ies, level=1)
        for ie_name in ies:
            yield getattr(mod, ie_name)

__ies = CachedGenerator(_load_extractors())

__ie_dict = {}

def gen_extractors():
    """ Return a list of an instance of every supported extractor.
    The order does matter; the first extractor matched is the one handling the URL.
    """
    return [ie() for ie in __ies]


def get_info_extractor(ie_name):
    """Returns the info extractor class with the given ie_name"""
    if not __ie_dict:
        __ie_dict.update(dict((ie.ie_key(), ie) for ie in __ies))
    return __ie_dict[ie_name]
